<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'BZContactButton\Core\PluginConfig' => $strauss_src . '/buttonizer/wp-php-core/src/PluginConfig.php',
   'BZContactButton\Core\InitBootstrap' => $strauss_src . '/buttonizer/wp-php-core/src/InitBootstrap.php',
   'BZContactButton\Core\Api\BaseApi' => $strauss_src . '/buttonizer/wp-php-core/src/Api/BaseApi.php',
   'BZContactButton\Core\Api\Connection\Sync' => $strauss_src . '/buttonizer/wp-php-core/src/Api/Connection/Sync.php',
   'BZContactButton\Core\Api\Connection\Disconnect' => $strauss_src . '/buttonizer/wp-php-core/src/Api/Connection/Disconnect.php',
   'BZContactButton\Core\Api\Connection\Connect' => $strauss_src . '/buttonizer/wp-php-core/src/Api/Connection/Connect.php',
   'BZContactButton\Core\Api\Connection\StartEditorSession' => $strauss_src . '/buttonizer/wp-php-core/src/Api/Connection/StartEditorSession.php',
   'BZContactButton\Core\Api\Analytics\Overview' => $strauss_src . '/buttonizer/wp-php-core/src/Api/Analytics/Overview.php',
   'BZContactButton\Core\Api\Settings\UpdateSettings' => $strauss_src . '/buttonizer/wp-php-core/src/Api/Settings/UpdateSettings.php',
   'BZContactButton\Core\Utils\Editor' => $strauss_src . '/buttonizer/wp-php-core/src/Utils/Editor.php',
   'BZContactButton\Core\Utils\ApiRequest' => $strauss_src . '/buttonizer/wp-php-core/src/Utils/ApiRequest.php',
   'BZContactButton\Core\Utils\PermissionCheck' => $strauss_src . '/buttonizer/wp-php-core/src/Utils/PermissionCheck.php',
   'BZContactButton\Core\Utils\SiblingPlugins' => $strauss_src . '/buttonizer/wp-php-core/src/Utils/SiblingPlugins.php',
   'BZContactButton\Core\Utils\ManifestParser' => $strauss_src . '/buttonizer/wp-php-core/src/Utils/ManifestParser.php',
   'BZContactButton\Core\Utils\Account' => $strauss_src . '/buttonizer/wp-php-core/src/Utils/Account.php',
   'BZContactButton\Core\Utils\Settings' => $strauss_src . '/buttonizer/wp-php-core/src/Utils/Settings.php',
   'BZContactButton\Core\Admin\BaseAdmin' => $strauss_src . '/buttonizer/wp-php-core/src/Admin/BaseAdmin.php',
   'BZContactButton\Core\Admin\AdminTemplate' => $strauss_src . '/buttonizer/wp-php-core/src/Admin/AdminTemplate.php',
);